### ISSUE TITLE
[Feature] Configure/expose external IP allocated for an edge

### ISSUE THREAD

**Issue by vfuyong** [terraform-providers/terraform-provider-vcd#397] opened 2019-11-17 08:03 UTC
Edge can automatically obtain an external IP from the pool, or explicitly configure an external IP. However, there is no way to specify external IP or read the allocated IP for an edge. The allocated external IP is required to configure other resources e.g. SNAT. 

### Terraform Version
2.5.0

### Affected Resource(s)
- vcd_edgegateway

### Expected Behavior
Edge should have an attribute for the allocated external IP

### Actual Behavior
Edge does not have an attribute for the allocated external IP

**Comment by Didainius** [comment] 2019-11-17 15:44
This is actually in progress. PR should arrive shortly

**Comment by Didainius** [comment] 2019-11-18 04:43
So to clarify this further on. The default external gateway IP is already merged via https://github.com/terraform-providers/terraform-provider-vcd/pull/389 (field name is still subject to change until official release).

While this https://github.com/terraform-providers/terraform-provider-vcd/issues/323 is very close to having a PR issue - today/tomorrow.

**Comment by Didainius** [comment] 2019-11-19 16:24
@vfuyong  - please check #323 as I'm closing this as duplicate of #323.

**Closed by Didainius** 2019-11-19 16:24 UTC

**Comment by Didainius** [comment] 2019-12-04 05:21
@vfuyong - this PR is merged to master. I'd appreciate if you can give it a spin and report if there are any issues as we are aiming for a a release soon.
