### ISSUE TITLE
Add vcd_network_routed data source

### ISSUE THREAD

**Issue by buec011** [terraform-providers/terraform-provider-vcd#330] opened 2019-09-16 13:47 UTC
The following data source will be useful for our workflows:
vcd_network_routed or short vcd_network. 

Inputs/Search Strings:
Network *name* (Optional, but then cidr_block required)
or 
*cidr_block* (Optional, but then name required, e.g. 192.168.0.0/24)
e.g:
```
data vcd_network mysubnet {
   name = "mysubnet"
}
```
Output/attributes should be 
*name*
and 
*cidr_block* similar to https://www.terraform.io/docs/providers/aws/d/subnet.html
e.g.
cidr_block = Networkadress/cidr , e.g. cidr_block=192.168.0.0/24
(OCI, AWS, Azure, Openstack provider have similar attributes with same output. Via terraform build in functions we can use this output further, e.g. https://www.terraform.io/docs/configuration/functions/cidrnetmask.html)
Maybe the following outputs are useful as well:
*type* (direct, routed, isolated)
*gateway* 

```
output "subnet_cidr" {
  value = data.aws_subnet.mysubnet.cidr_block
}
output "subnet_name" {
  value = data.aws_subnet.mysubnet.name
}
output "subnet_gw" {
  value = data.aws_subnet.mysubnet.gateway
}
output "subnet_routed" {
  value = data.aws_subnet.mysubnet.routed
}
```

**Comment by dataclouder** [comment] 2019-09-17 01:44
@buec011 ,
Please note that we have **three** network related resources, and that `vcd_network` is **deprecated**.
* [`vcd_network_isolated`](https://www.terraform.io/docs/providers/vcd/r/network_isolated.html)
* [`vcd_network_routed`](https://www.terraform.io/docs/providers/vcd/r/network_routed.html)
* [`vcd_network_direct`](https://www.terraform.io/docs/providers/vcd/r/network_direct.html)

Our plan (currently being developed) is to produce a data source for each of the above resources.

There is no `subnet_cidr` data available in the vCD data, although the GUI requires it that way. The data that is available for a `direct` network is 
* gateway
* netmask
* DNS1
* DNS2
* DNS suffix

The above fields can be introduced easily to `vcd_network_direct`.

**Comment by buec011** [comment] 2019-09-17 07:05
Hi @dataclouder ,
I'm aware that `vcd_network` is deprecated as a resource. To combine the data resource for network to one and just add a "type" attribute with values direct, routed, isolated was just a thought because otherwise you need to know in advance from which network type you want to load data. 
But for our workload it does not matter, most helpful will be a datasource for `vcd_network_routed`.
I will rename this issue for `vcd_network_routed` in particular

**Comment by dataclouder** [comment] 2019-09-17 07:15
Here is how the data source would work now (development in progress):

```hcl
data "vcd_network_routed" "net-datacloud-r" {
  name             = "net-datacloud-r"
  org              = "datacloud"
  vdc              = "vdc-datacloud"
  edge_gateway     = "gw-datacloud"
}

output "gateway" {
  value = data.vcd_network_routed.net-datacloud-r.gateway
}
output "netmask" {
  value = data.vcd_network_routed.net-datacloud-r.netmask
}
output "dns1" {
  value = data.vcd_network_routed.net-datacloud-r.dns1
}

output "start_address" {
  value = data.vcd_network_routed.net-datacloud-r.static_ip_pool[0].start_address
}
output "end_address" {
  value = data.vcd_network_routed.net-datacloud-r.static_ip_pool[0].end_address
}
```

and a sample output:

```
Outputs:

dns1 = 8.8.8.8
end_address = 192.168.2.100
gateway = 192.168.2.1
netmask = 255.255.255.0
start_address = 192.168.2.2
```

**Comment by buec011** [comment] 2019-09-17 08:07
Ok thanks. If the Pull Request is open I may be able to test.
It is a pity that netmask is not available as cidr notation, because terraform has a cidr to netmask:
https://www.terraform.io/docs/configuration/functions/cidrnetmask.html

But terraform does not have a netmask to cidr build-in function

**Comment by dataclouder** [comment] 2019-09-18 09:22
PR #333 addresses this issue

**Comment by dataclouder** [comment] 2019-09-25 11:32
@buec011 could you try the latest changes in PR #333 and see if it solves your problem?

**Comment by buec011** [comment] 2019-09-26 07:27
@dataclouder sorry, had been on a leave. Hopefully until end of next week

**Comment by dataclouder** [comment] 2019-09-26 08:29
The PR has been merged to master, so you can try master directly

**Comment by cheald** [comment] 2019-10-02 02:18
This seems to be failing all over the place for me. Operations which attempt to operate on networks by ID, rather than by name, now fail for me, as I don't appear to be getting URNs back from the VDC listing. Turning on SOAP debugging, I see:

```xml
    <AvailableNetworks>
        <Network href="https://myhost/api/network/bc4ef3ac-bc8e-4300-8913-78c3ebaf8109" name="az-internal" type="application/vnd.vmware.vcloud.network+xml"/>
        <Network href="https://myhost/api/network/26749307-e790-4dbe-9a2a-0c3146a6a4f5" name="az-public" type="application/vnd.vmware.vcloud.network+xml"/>
    </AvailableNetworks>
```

Note the suspicious lack of an `id` field in the Network element; I've confirmed that when attempting to match networks by ID, there is no ID to match against.

**Comment by lvirbalas** [comment] 2019-10-02 05:27
@cheald thanks for trying it out. Please see the section "Upgrading Network resources to 2.5" in the link below and let us know if it helps:
https://github.com/terraform-providers/terraform-provider-vcd/blob/master/TROUBLESHOOTING.md

**Comment by cheald** [comment] 2019-10-02 06:02
Unfortunately, this doesn't help. I'm working on a staging VPDC. I had resources previously created with Terraform 0.11 and a (much) earlier version of the provider, but when I couldn't get them to map the IDs, I blew it all away and started fresh. Even with a totally pristine state and completely empty VPDC, the provider fails to find networks after creating them, and furthermore fails to import them.

I'm set up to develop the plugin and can turn on logging or whatnot as would be helpful. I'm currently moving forward by just passing `name` rather than `id`, and it works just fine.

It looks like the vCloud Director platform we're on supports up to version 30.0, per the /api/versions endpoint. I'm not sure how to infer more specific information.

**Comment by vbauzysvmware** [comment] 2019-10-02 06:14
Hi @cheald could you try to reproduce this one more with this option enabled https://www.terraform.io/docs/providers/vcd/index.html#logging. 
It should generate a logfile with API calls. Double check if there is something you need to hide before sharing the config.
Also which version of vCD and NSX you are using? Is edge gateway advanced?

**Comment by cheald** [comment] 2019-10-02 06:26
Sure, here's the log. I created a new test vcd_network_routed and tried to apply it: https://gist.github.com/cheald/f8449c2f7b197ba7f9315749ada96736

I'm not sure which version of vCD or NSX these are; we don't own the vCD platform. Recent versions are available, though:

```
<VersionInfo deprecated="false">
  <Version>27.0</Version>
  <LoginUrl>https://vpdc.host.com/api/sessions</LoginUrl>
</VersionInfo>
<VersionInfo deprecated="false">
  <Version>28.0</Version>
  <LoginUrl>https://vpdc.host.com/api/sessions</LoginUrl>
</VersionInfo>
<VersionInfo deprecated="false">
  <Version>29.0</Version>
  <LoginUrl>https://vpdc.host.com/api/sessions</LoginUrl>
</VersionInfo>
<VersionInfo deprecated="false">
  <Version>30.0</Version>
  <LoginUrl>https://vpdc.host.com/api/sessions</LoginUrl>
</VersionInfo>
```

**Comment by vbauzysvmware** [comment] 2019-10-02 06:35
P.s. Seems your vCD version is 9.1 :)

**Comment by vbauzysvmware** [comment] 2019-10-02 07:52
OK. I confirmed your suspicions. There is different behaviour within API between version and with older version we don't get ID field within `AvailableNetworks\Network`. That's main culprit. Will will fix this.

**Comment by dataclouder** [comment] 2019-10-03 18:54
Please try again with 2.5 master. It should now work with 9.1 and beyond.

**Comment by cheald** [comment] 2019-10-03 21:02
Works well! Thank you!

**Comment by buec011** [comment] 2019-10-31 11:55
Hello,
please tell me if I should open a new bug, but we found a bug. If interface type of the routed network is "distributed" (we use a DLR), the data source fails. It is working with interface type "internal" or "subinterface" the data source is ok:

```
VCD 10
Terraform v0.12.12
provider 2.5
```

```
provider vcd {}
data "vcd_network_routed" "net" {
  name = "buec011-test"
}
```

```
> terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.vcd_network_routed.net: Refreshing state...

Error: [network_routed read] no edge gateway connection found for network buec011-test: no edge gateway connection found

  on main.tf line 18, in data "vcd_network_routed" "net":
  18: data "vcd_network_routed" "net" {
```

**Comment by dataclouder** [comment] 2019-11-11 08:55
@buec011 Please open a new issue for the distributed type triggering a failure.

**Closed** 2019-11-11 08:57 UTC

**Comment by buec011** [comment] 2019-11-11 09:15
> @buec011 Please open a new issue for the distributed type triggering a failure.

Done: https://github.com/terraform-providers/terraform-provider-vcd/issues/391
