### ISSUE TITLE
More than one IP pool in routed and isolated Org VDC networks

### ISSUE THREAD

**Issue by lvirbalas** [terraform-providers/terraform-provider-vcd#270] opened 2019-06-20 15:14 UTC
It is possible to define more than one IP pool for Org VDC networks as in the screen below:

![Screen Shot 2019-06-20 at 18 01 33](https://user-images.githubusercontent.com/11330689/59859805-22304400-9386-11e9-9c94-412ad27e07f0.png)

### Affected Resource(s)

- vcd_network_routed
- vcd_network_isolated

### Terraform Configuration Files

```hcl
# Org VDC network with more than one IP pool
# Only single "merged" pool is created currently 
resource "vcd_network_routed" "tf_net_multipool" {
  name         = "TfNetMultiPool"
  edge_gateway = "EdgeToVMware"

  gateway = "192.168.1.1"

  static_ip_pool {
    start_address = "192.168.1.2"
    end_address   = "192.168.1.100"
  }

  # Try adding second IP pool
  static_ip_pool {
    start_address = "192.168.1.101"
    end_address   = "192.168.1.105"
  }

  dhcp_pool {
    start_address = "192.168.1.200"
    end_address   = "192.168.1.230"
  }
}
```

### Debug Output

Resource created without any complains:

```
$ ../apply.sh
++ terraform apply -auto-approve -var-file=/Users/lvirbalas/terraform/configurations/environments.tfvars
vcd_network_routed.tf_net_multipool: Creating...
vcd_network_routed.tf_net_multipool: Still creating... [10s elapsed]
vcd_network_routed.tf_net_multipool: Still creating... [20s elapsed]
vcd_network_routed.tf_net_multipool: Still creating... [30s elapsed]
vcd_network_routed.tf_net_multipool: Creation complete after 34s [id=TfNetMultiPool]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

### Expected Behavior

Created network with two separate pools.

### Actual Behavior

Created network has one "merged" pool instead (note the beginning and ending IP address):

![Screen Shot 2019-06-20 at 18 08 43](https://user-images.githubusercontent.com/11330689/59860050-97037e00-9386-11e9-8d70-6606b6628ca7.png)

### Steps to Reproduce

1. `terraform apply`

**Comment by lvirbalas** [comment] 2019-06-20 15:14
FYI @Didainius and @vbauzysvmware

**Comment by dataclouder** [comment] 2019-11-28 17:08
This is not a bug. 
When the two pools are contiguous (e.g. first pool ends at `100`, second one starts at`101`), as in the example above, they are merged into one.
The behavior is consistent in both the API and in the UI. 

When the two pools have an interval between them, as in the example below, they are created separately.
```
  static_ip_pool {
    start_address = "10.10.102.2"
    end_address   = "10.10.102.100"
  }
  static_ip_pool {
    start_address = "10.10.102.102"
    end_address   = "10.10.102.105"
  }
```
In the example above, if you add the IP `10.10.102.101` (the missing IP between the two pools) to the pools in the UI and update the network, the two pools will be merged into one.

**Closed by dataclouder** 2019-11-28 17:08 UTC
Labels: bug
