### ISSUE TITLE
self.ip when using allocated returns "allocated" with provider 0.1.3 and 1.0.0

### ISSUE THREAD

**Issue by ckamps** [terraform-providers/terraform-provider-vcd#75] opened 2017-12-06 00:04 UTC
Similar to #50, but instead of using DHCP, in this case allocated mode is being used.

Terraform v0.11.1
Downloading plugin for provider "vcd" (1.0.0)...

References to `${self.ip}` result in the string "allocated" instead of the being set to actual IP address of the associated VM.  In Terraform v0.9.11, the proper IP address is returned.  

For example, when using the following code, the SSH connection eventually fails with the following error (IP address has been redacted):

```
dial tcp: lookup allocated on nn.nn.nn.nn:53: server misbehaving
```
Since SSH connection code is attempting to perform a DNS lookup using the IP address of "allocated" and this host is not defined in our DNS, errors occur and eventually the apply operation fails with an error.

Here's the example code:

```
resource "vcd_vapp" "instance" {
  name          = "${var.server_name}-${format("%.8s",uuid())}-${count.index}"
  catalog_name  = "${var.vcd_catalog}"
  template_name = "${var.vcd_template}"
  network_name  = "${var.vcd_network}"
  ip            = "allocated"
  count         = "${var.servers}"

  # Set up the SSH connection settings to be used in support of some of the subsequent provisioners.

  connection {
    host        = "${self.ip}"
    user        = "${var.ssh_user}"
    private_key = "${file("${var.ssh_private_key}")}"
    port        = "${var.ssh_port}"
  }
...
```

I believe PR #37 introduced this issue by forcing the `ip` to be hard coded to the string "allocated" when the "allocated" mode is in use. 

Ideally, PR #72 would be amended to fix this issue given that it's introducing code to separate specification of which IP allocation mode to use and the actual storage of the IP address.

**Comment by ckamps** [comment] 2017-12-12 00:20
When running with Terraform v0.11.1 and forcing the provide to be 0.1.1, this issue is NOT encountered.  Once I test with 0.1.2, I'll report back on that front.

```
provider "vcd" {
  version  = "0.1.1"
  ...
```

**Comment by dn1s** [comment] 2019-03-13 10:06
Duplicate of #50

**Closed** 2019-05-10 14:15 UTC
