### ISSUE TITLE
No way to create vApp with External Network

### ISSUE THREAD

**Issue by vahric** [terraform-providers/terraform-provider-vcd#91] opened 2018-06-06 16:57 UTC
Hello,

We are using External Networks (pre-configured vlan based )
I'm using  provider.vcd: version = "~> 1.0"
I guess this provider do not support set external network to vapp? 

Could you pls confirm ?

Any way to support it ? 
 
This is the code 

resource "vcd_vapp" "testvapp1" {
  name          = "testvapp1"
  power_on      = "false"
  network_name  = "external1"
}

**Comment by gregswift** [comment] 2018-07-02 17:23
If I'm understanding correctly, I believe this is working for us.  Our vcd_vapp looks just like yours.

What i can tell you is that when we started using terraform we had to remove the network from our catalog vapps because otherwise the network wouldnt get setup properly by terraform

**Comment by lvirbalas** [comment] 2018-11-16 03:31
@vahric I believe we have addressed external networks in vmware-takes-ownership branch (which we're planning to merge to master):
- I can confirm that just referencing in vApp an existing Org vDC Network which is directly attached to an External Network works
- In addition, we have recently added ability to create such directly attached networks with the help of a new resource `vcd_network_direct` as part of #95 

If you don't mind, I'll close this issue. Don't hesitate to reopen if there's more to it.

**Closed by lvirbalas** 2018-11-16 03:31 UTC
